import type { Metadata } from "next";
import { Poiret_One } from "next/font/google";
import "./globals.css";

const poiretOne = Poiret_One({
  weight: "400",
  variable: "--font-poiret-one",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${poiretOne.variable} antialiased`}>{children}</body>
    </html>
  );
}
